path = "/var/lib/rspamd/dkim/$domain.$selector.key";
selector = "mail";
selector_map = "/var/lib/rspamd/dkim/selectors.map";
sign_authenticated = true;
sign_local = true;
use_domain = "header";
use_esld = false;
allow_username_mismatch = true;
try_fallback = false;
